### ISSUE TITLE
关于zen mockserver与swagger的组合

### ISSUE THREAD

**Issue by lecer** [GalaxyTeam/conf-demo-2018#1]
想了解下在您设计的zen mockserver与swagger是如何组合搭配

掌握信息：
zen mockserver负责前端数据的产出，如特性可以生成swagger-data.json文件
swagger ui就是看api信息查阅，editor用来编辑产出api信息

问题：
swagger中又分ui与editor分别扮演什么角色？后台负责做些什么？
zen mockserver与swagger 的结合是如何进行的？
多项目是如何管理mock数据与swagger的？

**Comment by ufoqhmdt** [comment]
swagger中又分ui与editor分别扮演什么角色？后台负责做些什么？：

> editor是定义接口的开发者使用的工具，ui是使用接口的开发者。定义接口最好的方式就是接口的利益方全部参与定义，协议协议，就是一起协商议论，一个人定的接口不是协议。所以也不能说是基于协议。


zen mockserver与swagger 的结合是如何进行的？
> 很多时候开发着不喜欢json，或者另外一个开发者不喜欢yaml。所以我们做了一个工具把json和yaml打通。这样开发者想从那头开发都可以。

多项目是如何管理mock数据与swagger的？
> 如果前后端同学一起把接口定义好了，启动开发，因为没有接口，前端同学无法mock，效率会非常低，这个时候如果能在定义好接口的那一刻就基于swagger生成mock数据，那么对前端开发将会非常友好。所以我们把这个也做了。
